import type { Ticket } from "./types";

export const MOCK_BOOKINGS: Ticket[] = [
  {
    id: "1",
    created_at: new Date(),
    date: "2023-12-15",
    start_time: "10:00:00",
    end_time: "11:30:00",
    price: 49.99,
    service: "wash",
    status: "finished",
    secretary_id: "secretary-1",
    detailer_id: "detailer-1",
    cancel_reason: null,
    user: {
      id: "user-1",
      name: "John Doe",
      phone: "1234567890",
      email: "5dNl7@example.com",
      type: "user",
    },
    phone: "",
    note: "",
    location: "",
    secretary: null,
    detailer: null,
    rating: null,
  },
  {
    id: "2",
    created_at: new Date(),
    date: "2023-12-20",
    start_time: "14:00:00",
    end_time: "15:00:00",
    price: 29.99,
    service: "dryclean",
    status: "pending",
    secretary_id: "secretary-1",
    detailer_id: null,
    cancel_reason: null,
    user: {
      id: "user-1",
      name: "John Doe",
      phone: "1234567890",
      email: "5dNl7@example.com",
      type: "user",
    },
    phone: "",
    note: "",
    location: "",
    secretary: null,
    detailer: null,
    rating: null,
  },
  {
    id: "3",
    created_at: new Date(),
    date: null,
    start_time: null,
    end_time: null,
    price: 0,
    service: "polish",
    status: "requested",
    secretary_id: null,
    detailer_id: null,
    cancel_reason: null,
    user: {
      id: "user-1",
      name: "John Doe",
      phone: "1234567890",
      email: "5dNl7@example.com",
      type: "user",
    },
    phone: "",
    note: "",
    location: "",
    secretary: null,
    detailer: null,
    rating: null,
  },
];
